apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pastr-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: HelmCharts/ChartTest1
    repoURL: https://github.com/MaryiaDevOpsRoom/argocd-basic-setup.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
